server:
  port: 9014

spring:
  datasource:
    url: jdbc:postgresql://192.168.41.79:5432/hnzzrc?allowMultiQueries=true
    username: hnzzrc
    password: hnzzrc~123

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
