server:
  port: 9014

spring:
  datasource:
    url: jdbc:postgresql://10.70.33.20:5432/hnzzrc?allowMultiQueries=true
    username: postgres
    password: zzhr@2020

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
